### ISSUE TITLE
KeyError: 'supercategory'

### ISSUE THREAD

**Issue by yajieC** [dvlab-research/Entity#11]
When I run "python3 entity_to_json.py", the following problems occur：
Traceback (most recent call last):
  File "entity_to_json.py", line 23, in <module>
    catid_map                     = {category['id']: [cid, category["isthing"], category["name"], category["supercategory"]] for cid, category in enumerate(categories_list)}
  File "entity_to_json.py", line 23, in <dictcomp>
    catid_map                     = {category['id']: [cid, category["isthing"], category["name"], category["supercategory"]] for cid, category in enumerate(categories_list)}
KeyError: 'supercategory'

 I find that the problem occurs in categories_list,  and there is no "supercategory" key in categories_list(from detectron2.data.datasets.builtin_meta import COCO_CATEGORIES) .

**Comment by Chuny1** [comment]
Same Problem. 
You can download the json file from 'https://github.com/cocodataset/panopticapi/blob/master/panoptic_coco_categories.json' and load it as 'COCO_CATEGORIES'.
